### PR TITLE
Build py38 for Windows

### PR DESCRIPTION
**Pull request by dhirschfeld**
Checklist
* [ ] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by SylvainCorlay** [comment]
Hey @dhirschfeld thanks for opening this. I can't see the build logs.

Do you know what the issue is with ptvsd, windows, and Python 3.8?

**Comment by dhirschfeld** [comment]
>  I can't see the build logs.

@SylvainCorlay - no doubt deleted as it's been too long. I'll kick the CI to see what the issue was

**Comment by dhirschfeld** [comment]
@conda-forge-admin, please rerender

**Comment by dhirschfeld** [comment]
Looks like (on linux) an undefined variable bug in `conda-build=3.19.2`:
```
  File "/opt/conda/lib/python3.7/site-packages/conda_build/post.py", line 400, in mk_relative_osx
    log.warn("Found Mach-O file but patching is only supported on macOS, skipping: %s", path)
NameError: name 'log' is not defined
```
https://github.com/conda/conda-build/blob/3.19.2/conda_build/post.py#L400

...which is fixed in master:
https://github.com/conda/conda-build/blame/master/conda_build/post.py#L400
https://github.com/conda/conda-build/pull/3925

**Comment by dhirschfeld** [comment]
...but a couple of C errors on win64/py38:
```
 _pydevd_frame_eval\pydevd_frame_evaluator.c(7520): error C2037: left of 'eval_frame' specifies undefined struct/union '_is'
    _pydevd_frame_eval\pydevd_frame_evaluator.c(7619): error C2037: left of 'eval_frame' specifies undefined struct/union '_is'
```
https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=147497&view=logs&j=e5cdccbf-4751-5a24-7406-185c9d30d021&t=d66ed8ca-07ff-5419-c5d1-5e21fa500bb4&l=517

**Comment by dhirschfeld** [comment]
Superseded by #19

**Pull request closed without merging**
